AWSTemplateFormatVersion: '2010-09-09'
Conditions:
  CreateBucket:
    Fn::Equals:
    - Ref: CreateKinesisDestinationS3Bucket
    - 'yes'
Description: "A CloudFormation template that creates a role for authenticating with\
  \ Sumo\u2019s AWS integrations."
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Sumo Logic Deployment Configuration
      Parameters:
      - SumoDeployment
      - SumoAccessID
      - SumoAccessKey
    - Label:
        default: Sumo Logic Collection/Source Configuration
      Parameters:
      - CollectorName
      - SourceName
      - SourceCategoryName
      - PathExpression
      - ExternalID
      - RemoveSumoResourcesOnDeleteStack
    - Label:
        default: KinesisFirehose DeliveryStream Configuration
      Parameters:
      - DeliveryStreamName
    - Label:
        default: Kinesis Destination S3 Configuration
      Parameters:
      - KinesisDestinationS3BucketName
      - CreateKinesisDestinationS3Bucket
      - CompressionFormat
      - S3BackupMode
    ParameterLabels:
      CollectorName:
        default: Collector Name
      CreateS3Bucket:
        default: Do you want to create a target S3 bucket?
      DeliveryStreamName:
        default: Name of the delivery stream.
      ExternalID:
        default: IAM Role ExternalID
      KinesisDestinationS3BucketName:
        default: Target BucketName
      PathExpression:
        default: Path Expression
      RemoveSumoResourcesOnDeleteStack:
        default: Remove Sumo Resources On Delete Stack
      SourceCategoryName:
        default: Source Category
      SourceName:
        default: Source Name
      SumoAccessID:
        default: Access ID
      SumoAccessKey:
        default: Access Key
      SumoDeployment:
        default: Deployment Name
  AWS::ServerlessRepo::Application:
    Author: SumoLogic
    Description: SumoLogic AWS WAF Application
    HomePageUrl: https://github.com/SumoLogic/sumologic-aws-lambda
    Labels:
    - lambda
    - sumologic
    - serverless
    - WAF
    LicenseUrl: s3://sumologic-appdev-aws-sam-apps/ed96ade3777f01f35ff19f5db1a81893
    Name: sumologic-amazon-waf
    ReadmeUrl: s3://sumologic-appdev-aws-sam-apps/42d21e07634e6071d6f24789e5f8831e
    SemanticVersion: 0.0.1
    SourceCodeUrl: https://github.com/SumoLogic/sumologic-aws-lambda
    SpdxLicenseId: Apache-2.0
Parameters:
  CollectorName:
    Default: WAFCollector
    Type: String
  CompressionFormat:
    AllowedValues:
    - UNCOMPRESSED
    - GZIP
    - ZIP
    - Snappy
    Default: ZIP
    Type: String
  CreateKinesisDestinationS3Bucket:
    AllowedValues:
    - 'yes'
    - 'no'
    Default: 'no'
    Type: String
  DeliveryStreamName:
    Description: Name of the delivery stream.
    Type: String
  ExternalID:
    Description: An ID used in the trust policy to designate who can assume the role,
      formatted as deployment:accountId. Eg. us1:0000000000000131
    Type: String
  KinesisDestinationS3BucketName:
    Description: S3 access logs target buket name.
    Type: String
  PathExpression:
    Description: Path expression to match one or more S3 objects. For example, ABC*.log
      or ABC.log
    Type: String
  RemoveSumoResourcesOnDeleteStack:
    AllowedValues:
    - true
    - false
    Default: false
    Description: To delete collector, sources and app when stack is deleted, set this
      parameter to true. Default is false.
    Type: String
  S3BackupMode:
    AllowedValues:
    - Disabled
    - Enabled
    Default: Disabled
    Type: String
  SourceCategoryName:
    Description: Category metadata to use later for querying, e.g. prod/web/apache/access
      . This data is queried using the '_sourceCategory' key name.
    Type: String
  SourceName:
    Default: WAFEvents
    Type: String
  SumoAccessID:
    Type: String
  SumoAccessKey:
    Type: String
  SumoDeployment:
    AllowedValues:
    - au
    - ca
    - de
    - eu
    - jp
    - us2
    - us1
    Description: Enter au, ca, de, eu, jp, us2, or us1
    Type: String
Resources:
  KinesisDestinationS3Bucket:
    Condition: CreateBucket
    Properties:
      BucketName:
        Ref: KinesisDestinationS3BucketName
      NotificationConfiguration:
        TopicConfigurations:
        - Event: s3:ObjectCreated:Put
          Topic:
            Ref: sumoSNSTopic
    Type: AWS::S3::Bucket
  KinesisFirehoseDeliveryStream:
    Properties:
      DeliveryStreamName:
        Ref: DeliveryStreamName
      DeliveryStreamType: DirectPut
      ExtendedS3DestinationConfiguration:
        BucketARN:
          Fn::Sub: arn:aws:s3:::${KinesisDestinationS3BucketName}
        BufferingHints:
          IntervalInSeconds: 300
          SizeInMBs: 5
        CompressionFormat:
          Ref: CompressionFormat
        EncryptionConfiguration:
          NoEncryptionConfig: NoEncryption
        RoleARN:
          Fn::GetAtt:
          - KinesisS3Role
          - Arn
        S3BackupMode:
          Ref: S3BackupMode
    Type: AWS::KinesisFirehose::DeliveryStream
  KinesisS3Role:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Condition:
            StringEquals:
              sts:ExternalId:
                Ref: AWS::AccountId
          Effect: Allow
          Principal:
            Service: firehose.amazonaws.com
        Version: '2012-10-17'
      Path: /
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - s3:PutObject
            - s3:GetObject
            - s3:ListBucketMultipartUploads
            - s3:AbortMultipartUpload
            - s3:ListBucket
            - s3:GetBucketLocation
            Effect: Allow
            Resource:
            - Fn::Sub:
              - arn:aws:s3:::${S3bucketName}
              - S3bucketName:
                  Ref: KinesisDestinationS3BucketName
            - Fn::Sub:
              - arn:aws:s3:::${S3bucketName}/*
              - S3bucketName:
                  Ref: KinesisDestinationS3BucketName
          Version: '2012-10-17'
        PolicyName: KinesisS3RolePolicy
    Type: AWS::IAM::Role
  S3Source:
    Properties:
      CollectorId:
        Fn::GetAtt:
        - SumoHostedCollector
        - COLLECTOR_ID
      PathExpression:
        Ref: PathExpression
      Region:
        Ref: AWS::Region
      RemoveOnDeleteStack:
        Ref: RemoveSumoResourcesOnDeleteStack
      RoleArn:
        Fn::GetAtt:
        - SumoRole
        - Arn
      ServiceToken:
        Fn::GetAtt:
        - SumoAppUtils
        - Arn
      SourceCategory:
        Ref: SourceCategoryName
      SourceName:
        Ref: SourceName
      SumoAccessID:
        Ref: SumoAccessID
      SumoAccessKey:
        Ref: SumoAccessKey
      SumoDeployment:
        Ref: SumoDeployment
      TargetBucketName:
        Ref: KinesisDestinationS3BucketName
    Type: Custom::S3Source
  SumoAWSWAFApp:
    Properties:
      AppId: 87c2e6ca-a526-4745-af48-0c7225127b22
      AppName: AWS WAF
      AppSources:
        awsWAF:
          Fn::Sub: _sourceCategory=${SourceCategoryName}
      Region:
        Ref: AWS::Region
      RemoveOnDeleteStack:
        Ref: RemoveSumoResourcesOnDeleteStack
      ServiceToken:
        Fn::GetAtt:
        - SumoAppUtils
        - Arn
      SumoAccessID:
        Ref: SumoAccessID
      SumoAccessKey:
        Ref: SumoAccessKey
      SumoDeployment:
        Ref: SumoDeployment
    Type: Custom::App
  SumoAppUtils:
    Properties:
      CodeUri: s3://sumologic-appdev-aws-sam-apps/b12faf35c6433b87ceb947a18777125c
      Handler: main.handler
      MemorySize: 128
      Runtime: python3.7
      Timeout: 300
    Type: AWS::Serverless::Function
  SumoHostedCollector:
    Properties:
      CollectorName:
        Ref: CollectorName
      CollectorType: Hosted
      Region:
        Ref: AWS::Region
      RemoveOnDeleteStack:
        Ref: RemoveSumoResourcesOnDeleteStack
      ServiceToken:
        Fn::GetAtt:
        - SumoAppUtils
        - Arn
      SumoAccessID:
        Ref: SumoAccessID
      SumoAccessKey:
        Ref: SumoAccessKey
      SumoDeployment:
        Ref: SumoDeployment
    Type: Custom::Collector
  SumoRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Condition:
            StringEquals:
              sts:ExternalId:
                Ref: ExternalID
          Effect: Allow
          Principal:
            AWS: arn:aws:iam::926226587429:root
        Version: '2012-10-17'
      Path: /
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - s3:GetObject
            - s3:GetObjectVersion
            - s3:ListBucketVersions
            - s3:ListBucket
            Effect: Allow
            Resource:
            - Fn::Sub:
              - arn:aws:s3:::${S3bucketName}
              - S3bucketName:
                  Ref: KinesisDestinationS3BucketName
            - Fn::Sub:
              - arn:aws:s3:::${S3bucketName}/*
              - S3bucketName:
                  Ref: KinesisDestinationS3BucketName
          Version: '2012-10-17'
        PolicyName: SumoPolicy
    Type: AWS::IAM::Role
  sumoSNSSubscription:
    Properties:
      DeliveryPolicy:
        healthyRetryPolicy:
          backoffFunction: exponential
          maxDelayTarget: 300
          minDelayTarget: 10
          numMaxDelayRetries: 5
          numMinDelayRetries: 3
          numNoDelayRetries: 0
          numRetries: 40
      Endpoint:
        Fn::GetAtt:
        - S3Source
        - SUMO_ENDPOINT
      Protocol: https
      TopicArn:
        Ref: sumoSNSTopic
    Type: AWS::SNS::Subscription
  sumoSNSTopic:
    Properties:
      TopicName:
        Fn::Sub: SumoSNSTopic-${AWS::StackName}
    Type: AWS::SNS::Topic
  sumoSNSpolicy:
    Properties:
      PolicyDocument:
        Id: SumoTopicPolicy
        Statement:
        - Action: sns:Publish
          Condition:
            ArnLike:
              aws:SourceArn:
                Fn::Sub: arn:aws:s3:*:*:${KinesisDestinationS3BucketName}
            StringEquals:
              aws:SourceAccount:
                Ref: AWS::AccountId
          Effect: Allow
          Principal:
            AWS: '*'
          Resource:
            Ref: sumoSNSTopic
      Topics:
      - Ref: sumoSNSTopic
    Type: AWS::SNS::TopicPolicy
Transform: AWS::Serverless-2016-10-31
