AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A CloudFormation template that creates a role for authenticating with Sumo’s AWS integrations.

Metadata:
  
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Sumo Logic Deployment Configuration"
        Parameters:
          - SumoDeployment
          - SumoAccessID
          - SumoAccessKey
          - RemoveSumoResourcesOnDeleteStack
          - ExternalId
          - PathExpression
      -
        Label:
          default: "Sumo Logic GuardDuty Collector/Source/App Configuration"
        Parameters:
          - InstallGuardDutyApp
          - CollectorName
          - SourceName
          - SourceCategoryName
          
      -   
        Label:
          default: "Sumo Logic Amazon GuardDuty Benchmark Collector/Source/App Configuration"
        Parameters:
          - InstallGuardDutyBenchmarkApp
          - BenchmarkCollectorName
          - BenchmarkSourceName
          - BenchmarkSourceCategoryName
      
      -   
        Label:
          default: "Sumo Logic AWS CloudTrail Collector/Source/App Configuration"
        Parameters:
          - InstallCloudtrailApp
          - CloudTrailCollectorName
          - CloudTrailSourceName
          - CloudTrailSourceCategoryName
          - CloudTrailTargetS3BucketName
          - CreateCloudTrailTargetS3Bucket

      -   
        Label:
          default: "Sumo Logic AWS Config Collector/Source/App Configuration"
        Parameters:
          - InstallConfigApp
          - ConfigCollectorName
          - ConfigSourceName
          - ConfigSourceCategoryName
      
      -   
        Label:
          default: "Sumo Logic AWS CIS Foundations Benchmark Collector/Source/App Configuration"
        Parameters:
          - InstallCISFoundationsApp
          - CISFoundationsCollectorName
          - CISFoundationsSourceName
          - CISFoundationsSourceCategoryName
          - CISFoundationsTargetS3BucketName
          - CreateCISTargetS3Bucket

Parameters:
  SumoAccessID:
    Type: String
  SumoAccessKey:
    Type: String
  SumoDeployment:
    Type: String
    AllowedValues:
      - au
      - ca
      - de
      - eu
      - jp
      - us2
      - us1
    Description: "Enter au, ca, de, eu, jp, us2, or us1"
  RemoveSumoResourcesOnDeleteStack:
    AllowedValues:
      - true
      - false
    Default: false
    Description: To delete collector, sources and app when stack is deleted, set this parameter to true. Default is false.
    Type: String

  InstallGuardDutyApp:
    Type: String
    Default: "yes"
    AllowedValues:
      - "yes"
      - "no"
  CollectorName:
    Type: String
    Default: GuarddutyCollector
  SourceName:
    Type: String
    Default: GuarddutyEvents
  SourceCategoryName:
    Type: String
    Default: Labs/AWS/Guardduty

  InstallGuardDutyBenchmarkApp:
    Type: String
    Default: "yes"
    AllowedValues:
      - "yes"
      - "no"
  BenchmarkCollectorName:
    Type: String
    Default: GuarddutyBenchmarkCollector
  BenchmarkSourceName:
    Type: String
    Default: GuarddutyBenchmarkEvents
  BenchmarkSourceCategoryName:
    Type: String
    Default: Labs/AWS/Guardduty

  InstallCloudTrailApp:
    Type: String
    Default: "yes"
    AllowedValues:
      - "yes"
      - "no"
  CloudTrailCollectorName:
    Type: String
    Default: CloudTrailCollector
  CloudTrailSourceName:
    Type: String
    Default: CloudTrailEvents
  CloudTrailSourceCategoryName:
    Type: String
    Default: Labs/AWS/CloudTrail
  CloudTrailTargetS3BucketName:
    Type: String
  CreateCloudTrailTargetS3Bucket:
    Type: String
    Default: "no"
    AllowedValues:
      - "yes"
      - "no"
  PathExpression:
    Default: AWSLogs/*
    Type: String
  ExternalID:
    Description: An ID used in the trust policy to designate who can assume the role, formatted as deployment:accountId. Eg. us1:0000000000000131
    Type: String
  
  InstallConfigApp:
    Type: String
    Default: "yes"
    AllowedValues:
      - "yes"
      - "no"
  ConfigCollectorName:
    Type: String
    Default: ConfigCollector
  ConfigSourceName:
    Type: String
    Default: ConfigEvents
  ConfigSourceCategoryName:
    Type: String
    Default: Labs/AWS/Config
  
  InstallCISFoundationsApp:
    Type: String
    Default: "yes"
    AllowedValues:
      - "yes"
      - "no"
  CISFoundationsCollectorName:
    Type: String
    Default: CISFoundationsCollector
  CISFoundationsSourceName:
    Type: String
    Default: CISFoundationsEvents
  CISFoundationsSourceCategoryName]:
    Type: String
    Default: Labs/AWS/CISFoundations
  CISFoundationsTargetS3BucketName:
    Type: String
  CreateCISTargetS3Bucket:
    Type: String
    Default: "no"
    AllowedValues:
      - "yes"
      - "no"

  
Conditions:
  InstallGuardDutyCondition: !Equals [ !Ref InstallGuardDutyApp, "yes" ]
  InstallGuardDutyBenchmarkCondition: !Equals [ !Ref InstallGuardDutyBenchmarkApp, "yes" ]
  InstallCloudTrailCondition: !Equals [ !Ref InstallCloudtrailApp, "yes" ]
  InstallConfigCondition: !Equals [ !Ref InstallConfigApp, "yes" ]
  InstallCISFoundationsCondition: !Equals [ !Ref InstallCISFoundationsApp, "yes" ]

Resources:
  sumoguardduty:
    Condition: InstallGuardDutyCondition
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-west-2:296516481872:applications/sumo-guardduty
        SemanticVersion: 0.0.1
      Parameters: 
        CollectorName: !Ref CollectorName
        RemoveSumoResourcesOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
        SourceCategoryName: !Ref SourceCategoryName
        SourceName: !Ref SourceName
        SumoAccessID: !Ref SumoAccessID
        SumoAccessKey: !Ref SumoAccessKey
        SumoDeployment: !Ref SumoDeployment

  sumoguarddutybenchmark:
    Condition: InstallGuardDutyBenchmarkCondition
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-west-2:296516481872:applications/sumo-guardduty-bench-mark
        SemanticVersion: 0.0.1
      Parameters: 
        CollectorName: !Ref BenchmarkCollectorName
        RemoveSumoResourcesOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
        SourceCategoryName: !Ref BenchmarkSourceCategoryName
        SourceName: !Ref BenchmarkSourceName
        SumoAccessID: !Ref SumoAccessID
        SumoAccessKey: !Ref SumoAccessKey
        SumoDeployment: !Ref SumoDeployment  

  sumocloudtrail: 
    Condition: InstallCloudTrailCondition
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: "https://sumo-app-utils.s3-us-west-2.amazonaws.com/cloudtrail-packaged.yaml"
      Parameters: 
        CollectorName: !Ref CloudtrailCollectorName
        RemoveSumoResourcesOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
        SourceCategoryName: !Ref CloudtrailSourceCategoryName
        SourceName: !Ref CloudtrailSourceName
        SumoAccessID: !Ref SumoAccessID
        SumoAccessKey: !Ref SumoAccessKey
        SumoDeployment: !Ref SumoDeployment
        ExternalID: !Ref ExternalID
        PathExpression: !Ref PathExpression
        CloudTrailTargetS3BucketName: !Ref CloudTrailTargetS3BucketName   
        CreateTargetS3Bucket: !Ref CreateCloudTrailTargetS3Bucket
    
  sumoconfig:
    Condition: InstallConfigCondition
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-west-2:437178674894:applications/sumo-config
        SemanticVersion: 0.0.1
      Parameters: 
        CollectorName: !Ref ConfigCollectorName
        RemoveSumoResourcesOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
        SourceCategoryName: !Ref ConfigSourceCategoryName
        SourceName: !Ref ConfigSourceName
        SumoAccessID: !Ref SumoAccessID
        SumoAccessKey: !Ref SumoAccessKey
        SumoDeployment: !Ref SumoDeployment
    
  sumocisfoundations:
    Condition: InstallCISFoundationsCondition
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: "https://sumo-app-utils.s3-us-west-2.amazonaws.com/cis-foundations-packaged.yaml"
      Parameters: 
        CollectorName: !Ref CISFoundationsCollectorName
        RemoveSumoResourcesOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
        SourceCategoryName: !Ref CISFoundationsSourceCategoryName
        SourceName: !Ref CISFoundationsSourceName
        SumoAccessID: !Ref SumoAccessID
        SumoAccessKey: !Ref SumoAccessKey
        SumoDeployment: !Ref SumoDeployment
        ExternalID: !Ref ExternalID
        PathExpression: !Ref PathExpression
        CISTargetS3BucketName: !Ref CISFoundationsTargetS3BucketName 
        CreateTargetS3Bucket: !Ref CreateCISTargetS3Bucket