AWSTemplateFormatVersion: '2010-09-09'
Conditions:
  CreateBucket:
    Fn::Equals:
    - Ref: CreateTargetS3Bucket
    - 'yes'
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Sumo Logic Deployment Configuration
      Parameters:
      - SumoDeployment
      - SumoAccessID
      - SumoAccessKey
    - Label:
        default: Sumo Logic Collection Configuration
      Parameters:
      - CollectorName
      - SourceName
      - SourceCategoryName
      - PathExpression
      - RemoveSumoResourcesOnDeleteStack
    - Label:
        default: AWS Resources Configuration
      Parameters:
      - ExternalID
      - CloudTrailTargetS3BucketName
      - CreateTargetS3Bucket
    ParameterLabels:
      CloudTrailTargetS3BucketName:
        default: Target BucketName
      CollectorName:
        default: Collector Name
      CreateTargetS3Bucket:
        default: Do you want to create a target S3 bucket?
      ExternalID:
        default: IAM Role ExternalID
      PathExpression:
        default: Path Expression
      RemoveSumoResourcesOnDeleteStack:
        default: Remove Sumo Resources On Delete Stack
      SourceCategoryName:
        default: Source Category Name
      SourceName:
        default: Source Name
      SumoAccessID:
        default: Access ID
      SumoAccessKey:
        default: Access Key
      SumoDeployment:
        default: Deployment Name
  AWS::ServerlessRepo::Application:
    Author: SumoLogic
    Description: SumoLogic AWS CloudTrail Application
    HomePageUrl: https://github.com/SumoLogic/sumologic-aws-lambda
    Labels:
    - lambda
    - sumologic
    - serverless
    - cloudtrail
    LicenseUrl: s3://sumologic-appdev-aws-sam-apps/ed96ade3777f01f35ff19f5db1a81893
    Name: sumologic-amazon-cloudtrail
    ReadmeUrl: s3://sumologic-appdev-aws-sam-apps/28fa79f7855664fdc03fce826abc2855
    SemanticVersion: 0.0.1
    SourceCodeUrl: https://github.com/SumoLogic/sumologic-aws-lambda
    SpdxLicenseId: Apache-2.0
Outputs:
  SumoEndpoint:
    Description: SNS Subscription Endpoint
    Value:
      Fn::GetAtt:
      - SumoS3Source
      - SUMO_ENDPOINT
  SumoRoleArn:
    Description: ARN of the cretaed Role.
    Value:
      Fn::GetAtt:
      - SumoRole
      - Arn
Parameters:
  CloudTrailTargetS3BucketName:
    Description: CloudTrail logs target bucket name.
    Type: String
  CollectorName:
    Default: CloudTrailCollector
    Type: String
  CreateTargetS3Bucket:
    AllowedValues:
    - 'yes'
    - 'no'
    Default: 'no'
    Type: String
  ExternalID:
    Description: An ID used in the trust policy to designate who can assume the role,
      formatted as deployment:accountId. Eg. us1:0000000000000131
    Type: String
  PathExpression:
    Description: Path expression to match one or more S3 objects. For example, ABC*.log
      or ABC.log
    Type: String
  RemoveSumoResourcesOnDeleteStack:
    AllowedValues:
    - true
    - false
    Default: false
    Description: To delete collector, sources and app when stack is deleted, set this
      parameter to true. Default is false.
    Type: String
  SourceCategoryName:
    Type: String
  SourceName:
    Default: CloudTrailEvents
    Type: String
  SumoAccessID:
    Type: String
  SumoAccessKey:
    Type: String
  SumoDeployment:
    AllowedValues:
    - au
    - ca
    - de
    - eu
    - jp
    - us2
    - us1
    Description: Enter au, ca, de, eu, jp, us2, or us1
    Type: String
Resources:
  SumoAppUtils:
    Properties:
      CodeUri: s3://sumologic-appdev-aws-sam-apps/dd2eedea37882c6a51c487004e6379a5
      Handler: main.handler
      MemorySize: 128
      Runtime: python3.7
      Timeout: 300
    Type: AWS::Serverless::Function
  SumoCloudTrailApp:
    Properties:
      AppId: ceb7fac5-1137-4a04-a5b8-2e49190be3d4
      AppName: AWS CloudTrail
      AppSources:
        logsrc:
          Fn::Sub: _sourceCategory=${SourceCategoryName}
      Region:
        Ref: AWS::Region
      RemoveOnDeleteStack:
        Ref: RemoveSumoResourcesOnDeleteStack
      ServiceToken:
        Fn::GetAtt:
        - SumoAppUtils
        - Arn
      SumoAccessID:
        Ref: SumoAccessID
      SumoAccessKey:
        Ref: SumoAccessKey
      SumoDeployment:
        Ref: SumoDeployment
    Type: Custom::App
  SumoHostedCollector:
    Properties:
      CollectorName:
        Ref: CollectorName
      CollectorType: Hosted
      Region:
        Ref: AWS::Region
      RemoveOnDeleteStack:
        Ref: RemoveSumoResourcesOnDeleteStack
      ServiceToken:
        Fn::GetAtt:
        - SumoAppUtils
        - Arn
      SumoAccessID:
        Ref: SumoAccessID
      SumoAccessKey:
        Ref: SumoAccessKey
      SumoDeployment:
        Ref: SumoDeployment
    Type: Custom::Collector
  SumoRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Condition:
            StringEquals:
              sts:ExternalId:
                Ref: ExternalID
          Effect: Allow
          Principal:
            AWS: arn:aws:iam::926226587429:root
        Version: '2012-10-17'
      Path: /
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - s3:GetObject
            - s3:GetObjectVersion
            - s3:ListBucketVersions
            - s3:ListBucket
            Effect: Allow
            Resource:
            - Fn::Sub:
              - arn:aws:s3:::${CloudTrailTargetS3BucketName}
              - S3bucketName:
                  Ref: CloudTrailTargetS3BucketName
            - Fn::Sub:
              - arn:aws:s3:::${CloudTrailTargetS3BucketName}/*
              - S3bucketName:
                  Ref: CloudTrailTargetS3BucketName
          Version: '2012-10-17'
        PolicyName: SumoPolicy
    Type: AWS::IAM::Role
  SumoS3Source:
    DependsOn:
    - sumoS3BucketPolicy
    Properties:
      CollectorId:
        Fn::GetAtt:
        - SumoHostedCollector
        - COLLECTOR_ID
      PathExpression:
        Ref: PathExpression
      Region:
        Ref: AWS::Region
      RemoveOnDeleteStack:
        Ref: RemoveSumoResourcesOnDeleteStack
      RoleArn:
        Fn::GetAtt:
        - SumoRole
        - Arn
      ServiceToken:
        Fn::GetAtt:
        - SumoAppUtils
        - Arn
      SourceCategory:
        Ref: SourceCategoryName
      SourceName:
        Ref: SourceName
      SumoAccessID:
        Ref: SumoAccessID
      SumoAccessKey:
        Ref: SumoAccessKey
      SumoDeployment:
        Ref: SumoDeployment
      TargetBucketName:
        Ref: CloudTrailTargetS3BucketName
    Type: Custom::AwsCloudTrail
  TargetS3Bucket:
    Condition: CreateBucket
    DependsOn:
    - sumoSNSpolicy
    Properties:
      BucketName:
        Ref: CloudTrailTargetS3BucketName
      NotificationConfiguration:
        TopicConfigurations:
        - Event: s3:ObjectCreated:Put
          Topic:
            Ref: sumoSNSTopic
    Type: AWS::S3::Bucket
  sumoCloudTrail:
    DependsOn:
    - sumoS3BucketPolicy
    Properties:
      IsLogging: true
      IsMultiRegionTrail: false
      S3BucketName:
        Ref: CloudTrailTargetS3BucketName
      TrailName:
        Fn::Sub: SumoCloudTrail-${AWS::StackName}
    Type: AWS::CloudTrail::Trail
  sumoS3BucketPolicy:
    Properties:
      Bucket:
        Ref: CloudTrailTargetS3BucketName
      PolicyDocument:
        Statement:
        - Action: s3:GetBucketAcl
          Effect: Allow
          Principal:
            Service: cloudtrail.amazonaws.com
          Resource:
          - Fn::Sub: arn:aws:s3:::${CloudTrailTargetS3BucketName}
          Sid: AWSCloudTrailAclCheck
        - Action: s3:PutObject
          Condition:
            StringEquals:
              s3:x-amz-acl: bucket-owner-full-control
          Effect: Allow
          Principal:
            Service: cloudtrail.amazonaws.com
          Resource:
          - Fn::Sub: arn:aws:s3:::${CloudTrailTargetS3BucketName}/*
          Sid: AWSCloudTrailWrite
    Type: AWS::S3::BucketPolicy
  sumoSNSSubscription:
    Properties:
      DeliveryPolicy:
        healthyRetryPolicy:
          backoffFunction: exponential
          maxDelayTarget: 300
          minDelayTarget: 10
          numMaxDelayRetries: 5
          numMinDelayRetries: 3
          numNoDelayRetries: 0
          numRetries: 40
      Endpoint:
        Fn::GetAtt:
        - SumoS3Source
        - SUMO_ENDPOINT
      Protocol: https
      TopicArn:
        Ref: sumoSNSTopic
    Type: AWS::SNS::Subscription
  sumoSNSTopic:
    Properties:
      TopicName:
        Fn::Sub: SumoSNSTopic-${AWS::StackName}
    Type: AWS::SNS::Topic
  sumoSNSpolicy:
    Properties:
      PolicyDocument:
        Id: SumoTopicPolicy
        Statement:
        - Action:
          - sns:Publish
          Condition:
            ArnLike:
              aws:SourceArn:
                Fn::Sub: arn:aws:s3:::${CloudTrailTargetS3BucketName}
            StringEquals:
              aws:SourceAccount:
                Ref: AWS::AccountId
          Effect: Allow
          Principal:
            AWS: '*'
          Resource:
          - Ref: sumoSNSTopic
      Topics:
      - Ref: sumoSNSTopic
    Type: AWS::SNS::TopicPolicy
Transform: AWS::Serverless-2016-10-31
