AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A CloudFormation template that creates the required AWS resources for Sumo Logic App -- Payment Card Industry (PCI) Compliance for Amazon VPC Flow App.

Metadata:
  AWS::ServerlessRepo::Application:
    Name: sumo-amazon-pci-compliance-for-vpc-flow
    Description: Sumologic PCI Compliance for Amazon VPC Flow Application.
    Author: user1
    SpdxLicenseId: Apache-2.0
    LicenseUrl: ".\/..\/licence.txt"
    ReadmeUrl: ".\/README.md"
    Labels:
    - PCICompliance
    HomePageUrl: https://github.com/user1/my-app-project
    SemanticVersion: 0.0.1
    SourceCodeUrl: https://github.com/user1/my-app-project

  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Sumo Logic Deployment Configuration"
        Parameters:
          - SumoDeployment
          - SumoAccessID
          - SumoAccessKey
      -
        Label:
          default: "Sumo Logic Collector and Source Configuration"
        Parameters:
          - CollectorName
          - SourceName
          - SourceCategory
          - PathExpression
          - ExternalID
          - MultilineProcessingEnabled
          - ExcludeRuleName
          - ExcludeRule
          - PCIVpcFlowAppSourceCategory
      -
        Label:
          default: "S3 Configuration"
        Parameters:
          - LogsTargetS3BucketName
          - CreateTargetS3Bucket
    ParameterLabels:
      SumoDeployment:
        default: "Deployment Name"
      SumoAccessID:
        default: "Access ID"
      SumoAccessKey:
        default: "Access Key"
      CollectorName:
        default: "Collector Name"
      SourceName:
        default: "Source Name"
      SourceCategory:
        default: "Source Category"
      PathExpression:
        default: "Path Expression"
      
      RemoveSumoResourcesOnDeleteStack:
        default: "Remove Sumo Resources On Delete Stack"
      ExternalID:
        default: "IAM Role ExternalID"
      LogsTargetS3BucketName:
        default: "Target BucketName"
      CreateTargetS3Bucket:
        default: "Do you want to create a target S3 bucket?"

Parameters:
  CollectorName:
    Type: String
    Default: PCIVPCCollector
  SourceName:
    Type: String
    Default: PCIVPCSource
  SourceCategory:
    Type: String
    Description: Category metadata to use later for querying, e.g. prod/web/apache/access . This data is queried using the '_sourceCategory' key name.
  SumoAccessID:
    Type: String
  SumoAccessKey:
    Type: String
  SumoDeployment:
    Type: String
    AllowedValues:
      - au
      - ca
      - de
      - eu
      - jp
      - us2
      - us1
    Description: "Enter au, ca, de, eu, jp, us2, or us1"
  RemoveSumoResourcesOnDeleteStack:
    AllowedValues:
      - true
      - false
    Default: false
    Description: To delete collector, sources and app when stack is deleted, set this parameter to true. Default is false.
    Type: String
  ExternalID:
    Type: String
    Description: An ID used in the trust policy to designate who can assume the role, formatted as deployment:accountId. Eg. us1:0000000000000131
  LogsTargetS3BucketName:
    Type: String
    Description: S3 access logs target buket name.
  CreateTargetS3Bucket:
    Type: String
    Default: "no"
    AllowedValues: ["yes", "no"]
  PathExpression:
    Type: String
    Description: Path expression to match one or more S3 objects. For example, ABC*.log or ABC.log
  ExcludeRuleName:
    Type: String
    Default: Exclude VPC File Flow headers
  ExcludeRule:
    Type: String
    Description: Exclude rule regexp
    Default: version account-id interface-id srcaddr dstaddr srcport dstport protocol packets bytes start end action log-status
  PCIVpcFlowAppSourceCategory:
    Type: String
  S3SourceUtilTempalteS3Url:
    Type: String



Conditions:
  CreateBucket: !Equals [ !Ref CreateTargetS3Bucket, "yes" ]

Resources:
  
  sumoS3SourceStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref S3SourceUtilTempalteS3Url
      Parameters:
        SumoDeployment: !Ref SumoDeployment
        SumoAccessID: !Ref SumoAccessID
        SumoAccessKey: !Ref SumoAccessKey
        RemoveSumoResourcesOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
        CollectorName: !Ref CollectorName
        SourceName: !Ref SourceName
        LogsTargetS3BucketName: !Ref LogsTargetS3BucketName
        CreateTargetS3Bucket: !Ref CreateTargetS3Bucket
        SourceCategory: !Ref SourceCategory
        PathExpression: !Ref PathExpression
        ExternalID: !Ref ExternalID
        MultilineProcessingEnabled: False
        ExcludeRuleName: !Ref ExcludeRuleName
        ExcludeRule: !Ref ExcludeRule
  
  
  SumoAmazonS3AuditApp:
    Type: Custom::App
    Properties:
      ServiceToken: !GetAtt sumoS3SourceStack.Outputs.SumoAppUtilsArn
      Region: !Ref "AWS::Region"
      AppName: "PCI Compliance For Amazon VPC Flow"
      AppId: "afc4bae8-59af-41c0-b07d-c972400423e7"
      RemoveOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
      AppSources:
        AppLogSource: !Sub "_sourceCategory=${PCIVpcFlowAppSourceCategory}"
      SumoAccessID: !Ref SumoAccessID
      SumoAccessKey: !Ref SumoAccessKey
      SumoDeployment: !Ref SumoDeployment
      

