AWSTemplateFormatVersion: '2010-09-09'
Conditions:
  CreateBucket:
    Fn::Equals:
    - Ref: CreateTargetS3Bucket
    - 'yes'
Description: "A CloudFormation template that creates a role for authenticating with\
  \ Sumo\u2019s AWS integrations."
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Sumo Logic Deployment Configuration
      Parameters:
      - SumoDeployment
      - SumoAccessID
      - SumoAccessKey
      - RemoveSumoResourcesOnDeleteStack
    - Label:
        default: Sumo Logic Collector/Source/App Configuration
      Parameters:
      - CollectorName
      - SourceName
      - LogsTargetS3BucketName
      - CreateTargetS3Bucket
      - SourceCategoryName
      - PathExpression
      - ExternalID
      - ExcludeRuleName
      - ExcludeRule
      - VPCFlowLogAppSourceCategoryName
    ParameterLabels:
      CollectorName:
        default: Collector Name
      CreateTargetS3Bucket:
        default: Do you want to create a target S3 bucket?
      ExternalID:
        default: IAM Role ExternalID
      LogsTargetS3BucketName:
        default: Target BucketName
      PathExpression:
        default: Path Expression
      RemoveSumoResourcesOnDeleteStack:
        default: Remove Sumo Resources On Delete Stack
      SourceCategoryName:
        default: Source Category
      SourceName:
        default: Source Name
      SumoAccessID:
        default: Access ID
      SumoAccessKey:
        default: Access Key
      SumoDeployment:
        default: Deployment Name
      VPCFlowLogAppSourceCategoryName:
        default: Amazon VPC Flow Logs App SourceCategoryName
  AWS::ServerlessRepo::Application:
    Author: SumoLogic
    Description: SumoLogic Amazon VPC Flow Logs Application
    HomePageUrl: https://github.com/SumoLogic/sumologic-aws-lambda
    Labels:
    - lambda
    - sumologic
    - serverless
    - vpcFlowLogs
    LicenseUrl: s3://sumologic-appdev-aws-sam-apps/ed96ade3777f01f35ff19f5db1a81893
    Name: sumologic-amazon-vpc-flow-logs
    ReadmeUrl: s3://sumologic-appdev-aws-sam-apps/31e923d356476d8999c528271c66adac
    SemanticVersion: 0.0.1
    SourceCodeUrl: https://github.com/SumoLogic/sumologic-aws-lambda
    SpdxLicenseId: Apache-2.0
Outputs:
  SumoEndpoint:
    Description: SNS Subscription Endpoint
    Value:
      Fn::GetAtt:
      - SumoS3Source
      - SUMO_ENDPOINT
  SumoRoleArn:
    Description: ARN of the cretaed Role.
    Value:
      Fn::GetAtt:
      - SumoRole
      - Arn
Parameters:
  CollectorName:
    Default: VPCFlowLogCollector
    Type: String
  CreateTargetS3Bucket:
    AllowedValues:
    - 'yes'
    - 'no'
    Default: 'no'
    Type: String
  ExcludeRule:
    Default: version account-id interface-id srcaddr dstaddr srcport dstport protocol
      packets bytes start end action log-status
    Description: Exclude rule regexp
    Type: String
  ExcludeRuleName:
    Default: Exclude VPC File Flow headers
    Type: String
  ExternalID:
    Description: An ID used in the trust policy to designate who can assume the role,
      formatted as deployment:accountId. Eg. us1:0000000000000131
    Type: String
  LogsTargetS3BucketName:
    Description: S3 access logs target buket name.
    Type: String
  PathExpression:
    Description: Path expression to match one or more S3 objects. For example, ABC*.log
      or ABC.log
    Type: String
  RemoveSumoResourcesOnDeleteStack:
    AllowedValues:
    - true
    - false
    Default: false
    Description: To delete collector, sources and app when stack is deleted, set this
      parameter to true. Default is false.
    Type: String
  SourceCategoryName:
    Description: Category metadata to use later for querying, e.g. prod/web/apache/access
      . This data is queried using the '_sourceCategory' key name.
    Type: String
  SourceName:
    Default: VPCFlowLogEvents
    Type: String
  SumoAccessID:
    Type: String
  SumoAccessKey:
    Type: String
  SumoDeployment:
    AllowedValues:
    - au
    - ca
    - de
    - eu
    - jp
    - us2
    - us1
    Description: Enter au, ca, de, eu, jp, us2, or us1
    Type: String
  VPCFlowLogAppSourceCategoryName:
    Type: String
Resources:
  SumoAmazonVPCFlowLogAApp:
    Properties:
      AppId: 3546d789-3a45-48df-ac85-6838044d988d
      AppName: Amazon VPC Flow Logs
      AppSources:
        vpcFlowLogs:
          Fn::Sub: _sourceCategory=${VPCFlowLogAppSourceCategoryName}
      Region:
        Ref: AWS::Region
      RemoveOnDeleteStack:
        Ref: RemoveSumoResourcesOnDeleteStack
      ServiceToken:
        Fn::GetAtt:
        - SumoAppUtils
        - Arn
      SumoAccessID:
        Ref: SumoAccessID
      SumoAccessKey:
        Ref: SumoAccessKey
      SumoDeployment:
        Ref: SumoDeployment
    Type: Custom::App
  SumoAppUtils:
    Properties:
      CodeUri: s3://sumologic-appdev-aws-sam-apps/3b29de557a2ead091a3590dcf6bb8f7c
      Handler: main.handler
      MemorySize: 128
      Runtime: python3.7
      Timeout: 300
    Type: AWS::Serverless::Function
  SumoHostedCollector:
    Properties:
      CollectorName:
        Ref: CollectorName
      CollectorType: Hosted
      Region:
        Ref: AWS::Region
      RemoveOnDeleteStack:
        Ref: RemoveSumoResourcesOnDeleteStack
      ServiceToken:
        Fn::GetAtt:
        - SumoAppUtils
        - Arn
      SumoAccessID:
        Ref: SumoAccessID
      SumoAccessKey:
        Ref: SumoAccessKey
      SumoDeployment:
        Ref: SumoDeployment
    Type: Custom::Collector
  SumoRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Condition:
            StringEquals:
              sts:ExternalId:
                Ref: ExternalID
          Effect: Allow
          Principal:
            AWS: arn:aws:iam::926226587429:root
        Version: '2012-10-17'
      Path: /
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - s3:GetObject
            - s3:GetObjectVersion
            - s3:ListBucketVersions
            - s3:ListBucket
            Effect: Allow
            Resource:
            - Fn::Sub:
              - arn:aws:s3:::${S3bucketName}
              - S3bucketName:
                  Ref: LogsTargetS3BucketName
            - Fn::Sub:
              - arn:aws:s3:::${S3bucketName}/*
              - S3bucketName:
                  Ref: LogsTargetS3BucketName
          Version: '2012-10-17'
        PolicyName: SumoPolicy
    Type: AWS::IAM::Role
  SumoS3Source:
    Properties:
      CollectorId:
        Fn::GetAtt:
        - SumoHostedCollector
        - COLLECTOR_ID
      PathExpression:
        Ref: PathExpression
      Region:
        Ref: AWS::Region
      RemoveOnDeleteStack:
        Ref: RemoveSumoResourcesOnDeleteStack
      RoleArn:
        Fn::GetAtt:
        - SumoRole
        - Arn
      ServiceToken:
        Fn::GetAtt:
        - SumoAppUtils
        - Arn
      SourceCategory:
        Ref: SourceCategoryName
      SourceName:
        Ref: SourceName
      SumoAccessID:
        Ref: SumoAccessID
      SumoAccessKey:
        Ref: SumoAccessKey
      SumoDeployment:
        Ref: SumoDeployment
      TargetBucketName:
        Ref: LogsTargetS3BucketName
      autolineMatching": false
      filters:
      - filterType: Exclude
        name:
          Ref: ExcludeRuleName
        regexp:
          Ref: ExcludeRule
      multilineProessing: false
    Type: Custom::S3Source
  TargetS3Bucket:
    Condition: CreateBucket
    Properties:
      BucketName:
        Ref: LogsTargetS3BucketName
      NotificationConfiguration:
        TopicConfigurations:
        - Event: s3:ObjectCreated:Put
          Topic:
            Ref: sumoS3SorceTopic
    Type: AWS::S3::Bucket
  sumoS3SorceTopic:
    Properties:
      TopicName:
        Fn::Sub: SumoSNSTopic-${AWS::StackName}
    Type: AWS::SNS::Topic
  sumoSNSSubscription:
    Properties:
      DeliveryPolicy:
        healthyRetryPolicy:
          backoffFunction: exponential
          maxDelayTarget: 300
          minDelayTarget: 10
          numMaxDelayRetries: 5
          numMinDelayRetries: 3
          numNoDelayRetries: 0
          numRetries: 40
      Endpoint:
        Fn::GetAtt:
        - SumoS3Source
        - SUMO_ENDPOINT
      Protocol: https
      TopicArn:
        Ref: sumoS3SorceTopic
    Type: AWS::SNS::Subscription
  sumoSNSpolicy:
    Properties:
      PolicyDocument:
        Id: SumoTopicPolicy
        Statement:
        - Action: sns:Publish
          Condition:
            ArnLike:
              aws:SourceArn:
                Fn::Sub: arn:aws:s3:*:*:${LogsTargetS3BucketName}
            StringEquals:
              aws:SourceAccount:
                Ref: AWS::AccountId
          Effect: Allow
          Principal:
            AWS: '*'
          Resource:
            Ref: sumoS3SorceTopic
      Topics:
      - Ref: sumoS3SorceTopic
    Type: AWS::SNS::TopicPolicy
Transform: AWS::Serverless-2016-10-31
