AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A CloudFormation template that creates a role for authenticating with Sumo’s AWS integrations.

Metadata:

  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Sumo Logic Deployment Configuration"
        Parameters:
          - SumoDeployment
          - SumoAccessID
          - SumoAccessKey
          - RemoveSumoResourcesOnDeleteStack
          - SumoOrganizationId
      -
        Label:
          default: "Select the Sumo Apps that you want to Deploy:"
        Parameters:
          - InstallPCICloudTrailApp
          - InstallPCIVPCFlowLogsApp

      -
        Label:
          default: "Sumo Logic PCI Compliance for Amazon VPC Flow Logs Collector/App Configuration"
        Parameters:
          - PCIVPCSourceCategory
          - PCIVPCPathExpression
          - PCIVPCLogsTargetS3BucketName
          - PCIVPCCreateTargetS3Bucket

Parameters:
  SumoOrganizationId:
    Type: String
  SumoAccessID:
    Type: String
  SumoAccessKey:
    Type: String
  SumoDeployment:
    Type: String
    AllowedValues:
      - au
      - ca
      - de
      - eu
      - jp
      - us2
      - us1
    Description: "Enter au, ca, de, eu, jp, us2, or us1"
  RemoveSumoResourcesOnDeleteStack:
    AllowedValues:
      - true
      - false
    Default: true
    Description: To delete collector, sources and app when stack is deleted, set this parameter to true. Default is false.
    Type: String

  InstallPCIVPCFlowLogsApp:
    Type: String
    Default: "yes"
    AllowedValues:
      - "yes"
      - "no"
  PCIVPCSourceCategory:
    Type: String
  PCIVPCPathExpression:
    Type: String
  PCIVPCLogsTargetS3BucketName:
    Type: String
  PCIVPCCreateTargetS3Bucket:
    Type: String
    Default: "yes"
    AllowedValues: ["yes", "no"]
    Description: "Do you want to create a target S3 bucket?"


Conditions:
  InstallPCIVPCFlowLogsCondition: !Equals [ !Ref InstallPCIVPCFlowLogsApp, "yes" ]

Resources:
  sumoPCIVPCFlowLogsStack:
    Type: AWS::CloudFormation::Stack
    Condition: InstallPCIVPCFlowLogsCondition
    Properties:
      TemplateURL: "https://sumologic-appdev-aws-sam-apps.s3.amazonaws.com/pci-compliance-vpc-flow-template-2019-11-05-16-46-11.yaml"
      Parameters:
        S3SourceUtilTempalteS3Url: "https://sumologic-appdev-aws-sam-apps.s3.amazonaws.com/sumo-s3-source-utils-2019-11-05-16-45-59.yaml"
        SumoDeployment: !Ref SumoDeployment
        SumoAccessID: !Ref SumoAccessID
        SumoAccessKey: !Ref SumoAccessKey
        RemoveSumoResourcesOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
        CollectorName: "QuickStart-PCIComplianceforAmazonVPCFlowLogs"
        SourceCategory: !Ref PCIVPCSourceCategory
        LogsTargetS3BucketName: !Ref PCIVPCLogsTargetS3BucketName
        CreateTargetS3Bucket: !Ref PCIVPCCreateTargetS3Bucket
        PCIVpcFlowAppSourceCategory: !Ref PCIVPCSourceCategory
        SourceName: "PCIComplianceforAmazonVPCFlowLogs"
        PathExpression: !Ref PCIVPCPathExpression
        ExternalID: !Sub "${SumoDeployment}:${SumoOrganizationId}"


