AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A CloudFormation template that creates a role for authenticating with Sumo’s AWS integrations.

Metadata:

  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Sumo Logic Deployment Configuration"
        Parameters:
          - SumoDeployment
          - SumoAccessID
          - SumoAccessKey
          - RemoveSumoResourcesOnDeleteStack
          - SumoOrganizationId
      -
        Label:
          default: "Select the Sumo Apps that you want to Deploy:"
        Parameters:
          - InstallCISFoundationsApp

      -
        Label:
          default: "Sumo Logic AWS CIS Foundations Benchmark Collector/Source/App Configuration"
        Parameters:
          - CISFoundationsCollectorName
          - CISFoundationsSourceName
          - CISFoundationsTargetS3BucketName
          - CISFoundationsSourceCategoryName
          - CreateCISFoundationsTargetS3Bucket
          - CISFoundationsPathExpression

Parameters:
  SumoAccessID:
    Type: String
  SumoAccessKey:
    Type: String
  SumoDeployment:
    Type: String
    AllowedValues:
      - au
      - ca
      - de
      - eu
      - jp
      - us2
      - us1
    Description: "Enter au, ca, de, eu, jp, us2, or us1"
  RemoveSumoResourcesOnDeleteStack:
    AllowedValues:
      - true
      - false
    Default: true
    Description: To delete collector, sources and app when stack is deleted, set this parameter to true. Default is false.
    Type: String
  SumoOrganizationId:
    Type: String

  InstallCISFoundationsApp:
    Type: String
    Default: "yes"
    AllowedValues:
      - "yes"
      - "no"
  CISFoundationsCollectorName:
    Type: String
    Default: CISFoundationsCollector
  CISFoundationsSourceName:
    Type: String
    Default: CISFoundationsEvents
  CISFoundationsSourceCategoryName:
    Type: String
    Description: Category metadata to use later for querying, e.g. prod/web/apache/access . This data is queried using the '_sourceCategory' key name.
    Default: access
  CISFoundationsPathExpression:
    Type: String
    Description: Path expression to match one or more S3 objects. For example, ABC*.log or ABC.log
    Default: "*"
  CISFoundationsTargetS3BucketName:
    Type: String
    Default: "cis-foundations-benchmark-s3-bucket"
    Description: S3 access logs target buket name.
  CreateCISFoundationsTargetS3Bucket:
    Type: String
    Default: "yes"
    AllowedValues: ["yes", "no"]
    Description: "Do you want to create a target S3 bucket?"

Conditions:
  InstallCISFoundationsCondition: !Equals [ !Ref InstallCISFoundationsApp, "yes" ]

Resources:

  sumocisfoundations:
    Condition: InstallCISFoundationsCondition
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://sumologic-appdev-aws-sam-apps.s3.amazonaws.com/CIS-Foundations-template-2019-10-30-18-09-08.yaml"
      Parameters:
        CollectorName: !Ref CISFoundationsCollectorName
        RemoveSumoResourcesOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
        SourceCategoryName: !Ref CISFoundationsSourceCategoryName
        SourceName: !Ref CISFoundationsSourceName
        SumoAccessID: !Ref SumoAccessID
        SumoAccessKey: !Ref SumoAccessKey
        SumoDeployment: !Ref SumoDeployment
        ExternalID: !Sub "${SumoDeployment}:${SumoOrganizationId}"
        PathExpression: !Ref CISFoundationsPathExpression
        CISTargetS3BucketName: !Ref CISFoundationsTargetS3BucketName
        CreateTargetS3Bucket: !Ref CreateCISFoundationsTargetS3Bucket


