AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A CloudFormation template that creates a role for authenticating with Sumo’s AWS integrations.

Metadata:

  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Sumo Logic Deployment Configuration"
        Parameters:
          - SumoDeployment
          - SumoAccessID
          - SumoAccessKey
          - RemoveSumoResourcesOnDeleteStack
          - SumoOrganizationId
      -
        Label:
          default: "Select the Sumo Apps that you want to Deploy:"
        Parameters:
          - InstallCloudTrailApp

      -
        Label:
          default: "Sumo Logic AWS CloudTrail Collector/Source/App Configuration"
        Parameters:
          - CloudTrailCollectorName
          - CloudTrailSourceName
          - CloudTrailTargetS3BucketName
          - CreateCloudTrailTargetS3Bucket
          - CloudTrailSourceCategoryName
          - CloudTrailPathExpression


Parameters:
  SumoAccessID:
    Type: String
  SumoAccessKey:
    Type: String
  SumoDeployment:
    Type: String
    AllowedValues:
      - au
      - ca
      - de
      - eu
      - jp
      - us2
      - us1
    Description: "Enter au, ca, de, eu, jp, us2, or us1"
  RemoveSumoResourcesOnDeleteStack:
    AllowedValues:
      - true
      - false
    Default: true
    Description: To delete collector, sources and app when stack is deleted, set this parameter to true. Default is false.
    Type: String
  SumoOrganizationId:
    Type: String

  InstallCloudTrailApp:
    Type: String
    Default: "yes"
    AllowedValues:
      - "yes"
      - "no"
  CloudTrailCollectorName:
    Type: String
    Default: CloudTrailCollector
  CloudTrailSourceName:
    Type: String
    Default: CloudTrailEvents
  CloudTrailSourceCategoryName:
    Type: String
    Description: Category metadata to use later for querying, e.g. prod/web/apache/access . This data is queried using the '_sourceCategory' key name.
    Default: access
  CloudTrailPathExpression:
    Type: String
    Description: Path expression to match one or more S3 objects. For example, ABC*.log or ABC.log
    Default: "*"
  CloudTrailTargetS3BucketName:
    Type: String
    Default: "cloud-trail-s3-bucket"
    Description: S3 access logs target buket name.
  CreateCloudTrailTargetS3Bucket:
    Type: String
    Default: "yes"
    AllowedValues: ["yes", "no"]
    Description: "Do you want to create a target S3 bucket?"

Conditions:
  InstallCloudTrailCondition: !Equals [ !Ref InstallCloudTrailApp, "yes" ]

Resources:
  sumocloudtrail:
    Condition: InstallCloudTrailCondition
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://sumologic-appdev-aws-sam-apps.s3.amazonaws.com/cloudtrail-template-2019-10-30-17-54-17.yaml"
      Parameters:
        CollectorName: !Ref CloudTrailCollectorName
        RemoveSumoResourcesOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
        SourceCategoryName: !Ref CloudTrailSourceCategoryName
        SourceName: !Ref CloudTrailSourceName
        SumoAccessID: !Ref SumoAccessID
        SumoAccessKey: !Ref SumoAccessKey
        SumoDeployment: !Ref SumoDeployment
        ExternalID: !Sub "${SumoDeployment}:${SumoOrganizationId}"
        PathExpression: !Ref CloudTrailPathExpression
        CloudTrailTargetS3BucketName: !Ref CloudTrailTargetS3BucketName
        CreateTargetS3Bucket: !Ref CreateCloudTrailTargetS3Bucket


