AWSTemplateFormatVersion: '2010-09-09'
Conditions:
  CreateBucket:
    Fn::Equals:
    - Ref: CreateTargetS3Bucket
    - 'yes'
Description: A CloudFormation template that creates the required AWS resources for
  Sumo Logic App -- Payment Card Industry (PCI) Compliance for AWS CloudTrail App.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Sumo Logic Deployment Configuration
      Parameters:
      - SumoDeployment
      - SumoAccessID
      - SumoAccessKey
    - Label:
        default: Sumo Logic Collector and Source Configuration
      Parameters:
      - CollectorName
      - SourceName
      - SourceCategory
      - PathExpression
      - ExternalID
      - PCICloudTrailAppSourceCategory
    - Label:
        default: S3 Configuration
      Parameters:
      - LogsTargetS3BucketName
      - CreateTargetS3Bucket
    ParameterLabels:
      CollectorName:
        default: Collector Name
      CreateTargetS3Bucket:
        default: Do you want to create a target S3 bucket?
      ExternalID:
        default: IAM Role ExternalID
      LogsTargetS3BucketName:
        default: Target BucketName
      PathExpression:
        default: Path Expression
      RemoveSumoResourcesOnDeleteStack:
        default: Remove Sumo Resources On Delete Stack
      SourceCategory:
        default: Source Category
      SourceName:
        default: Source Name
      SumoAccessID:
        default: Access ID
      SumoAccessKey:
        default: Access Key
      SumoDeployment:
        default: Deployment Name
  AWS::ServerlessRepo::Application:
    Author: SumoLogic
    Description: Sumologic PCI Compliance for AWS CloudTrail App.
    HomePageUrl: https://github.com/SumoLogic/sumologic-aws-lambda
    Labels:
    - lambda
    - sumologic
    - serverless
    - cloudtrail
    - PCICompliance
    LicenseUrl: s3://sumologic-appdev-aws-sam-apps/ed96ade3777f01f35ff19f5db1a81893
    Name: sumologic-amazon-pci-compliance-for-cloudtrail
    ReadmeUrl: s3://sumologic-appdev-aws-sam-apps/edfb3549ceb6e812eefc409e77c7848d
    SemanticVersion: 0.0.1
    SourceCodeUrl: https://github.com/SumoLogic/sumologic-aws-lambda
    SpdxLicenseId: Apache-2.0
Parameters:
  CollectorName:
    Default: PCIVPCCollector
    Type: String
  CreateTargetS3Bucket:
    AllowedValues:
    - 'yes'
    - 'no'
    Default: 'no'
    Type: String
  ExcludeRule:
    Default: version account-id interface-id srcaddr dstaddr srcport dstport protocol
      packets bytes start end action log-status
    Description: Exclude rule regexp
    Type: String
  ExcludeRuleName:
    Default: Exclude VPC File Flow headers
    Type: String
  ExternalID:
    Description: An ID used in the trust policy to designate who can assume the role,
      formatted as deployment:accountId. Eg. us1:0000000000000131
    Type: String
  LogsTargetS3BucketName:
    Description: S3 access logs target buket name.
    Type: String
  PCICloudTrailAppSourceCategory:
    Type: String
  PathExpression:
    Description: Path expression to match one or more S3 objects. For example, ABC*.log
      or ABC.log
    Type: String
  RemoveSumoResourcesOnDeleteStack:
    AllowedValues:
    - true
    - false
    Default: false
    Description: To delete collector, sources and app when stack is deleted, set this
      parameter to true. Default is false.
    Type: String
  S3SourceUtilTempalteS3Url:
    Type: String
  SourceCategory:
    Description: Category metadata to use later for querying, e.g. prod/web/apache/access
      . This data is queried using the '_sourceCategory' key name.
    Type: String
  SourceName:
    Default: PCIVPCSource
    Type: String
  SumoAccessID:
    Type: String
  SumoAccessKey:
    Type: String
  SumoDeployment:
    AllowedValues:
    - au
    - ca
    - de
    - eu
    - jp
    - us2
    - us1
    Description: Enter au, ca, de, eu, jp, us2, or us1
    Type: String
Resources:
  sumoAmazonS3AuditApp:
    Properties:
      AppId: 924d7e2a-a14a-4b11-8c91-133241be2a51
      AppName: PCI Compliance For AWS CloudTrail.
      AppSources:
        AppLogSource:
          Fn::Sub: _sourceCategory=${PCICloudTrailAppSourceCategory}
      Region:
        Ref: AWS::Region
      RemoveOnDeleteStack:
        Ref: RemoveSumoResourcesOnDeleteStack
      ServiceToken:
        Fn::GetAtt:
        - sumoCloudTrailSourceStack
        - Outputs.SumoAppUtilsArn
      SumoAccessID:
        Ref: SumoAccessID
      SumoAccessKey:
        Ref: SumoAccessKey
      SumoDeployment:
        Ref: SumoDeployment
    Type: Custom::App
  sumoCloudTrailSourceStack:
    Properties:
      Parameters:
        CollectorName:
          Ref: CollectorName
        CreateTargetS3Bucket:
          Ref: CreateTargetS3Bucket
        ExcludeRule: None
        ExcludeRuleName: None
        ExternalID:
          Ref: ExternalID
        LogsTargetS3BucketName:
          Ref: LogsTargetS3BucketName
        MultilineProcessingEnabled: true
        PathExpression:
          Ref: PathExpression
        RemoveSumoResourcesOnDeleteStack:
          Ref: RemoveSumoResourcesOnDeleteStack
        SourceCategory:
          Ref: SourceCategory
        SourceName:
          Ref: SourceName
        SumoAccessID:
          Ref: SumoAccessID
        SumoAccessKey:
          Ref: SumoAccessKey
        SumoDeployment:
          Ref: SumoDeployment
        SumoSourceType: AwsCloudTrail
      TemplateURL:
        Ref: S3SourceUtilTempalteS3Url
    Type: AWS::CloudFormation::Stack
Transform: AWS::Serverless-2016-10-31
