AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'This solution consists of a lambda function which which gets triggered
  when CF stack is deployed. This is used for creating sumologic resources like collector,
  source and app folders.

  '
Globals:
  Function:
    Timeout: 300
Metadata:
  AWS::ServerlessRepo::Application:
    Name: sumo-app-util
    Description: SumoAppUtils
    Author: user1
    SpdxLicenseId: Apache-2.0
    LicenseUrl: s3://sumo-ct-app-bucket/60dd855ef60687184c3b1f69ed374378
    ReadmeUrl: s3://sumo-ct-app-bucket/4d5a92c06a7fa9d956a900e51a1f6be4
    Labels:
    - tests
    HomePageUrl: https://github.com/user1/my-app-project
    SemanticVersion: 0.0.1
    SourceCodeUrl: https://github.com/user1/my-app-project
Resources:
  SumoAppUtilsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.handler
      Runtime: python3.7
      CodeUri: s3://sumo-ct-app-bucket/5288189d413b10ea17cb2e3b5f82ae9b
      MemorySize: 128
      Timeout: 300
Outputs:
  SumoAppUtilsFunction:
    Description: SumoAppUtils Function ARN
    Value:
      Fn::GetAtt:
      - SumoAppUtilsFunction
      - Arn
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-SumoAppUtilsFunction
